<div class="github-connect">
    <div class="page-title">
        <h1><?php echo $this->__('Github Connect') ?></h1>
    </div>
    <?php if($this->_hasUserInfo()):
        $user_data = $this->user_info();
        $githubId = $user_data['github_id'];
        $fullname = $user_data['fullname'];
        $email = $user_data['email'];
        $html_url = $user_data['html_url'];
        $picture = $user_data['profile_image'];
        $company = $user_data['company'];
        $github_username =  $user_data['github_username'];
    ?>
    <div class="col3-set">
        <div class="box">
            <div class="box-content">        
                <div class="col-1" style="width:40%;float:left;">                   
                    <?php if(!empty($picture)): ?>
                    <p>
                        <img src="<?php echo $picture; ?>" alt="<?php echo $this->htmlEscape($github_username); ?>" width="100px" />
                    </p>
                    <p>&nbsp;</p>
                    <?php endif; ?>
                </div>
                <div class="col-2">                          
                    <?php if(!empty($email)): ?>
                    <p>
                        <?php printf($this->__('Email: %s', '<strong>'.$email.'</strong>')) ?>
                    </p>
                    <?php endif; ?>                
                    <?php if(!empty($githubId)): ?>
                    <p>                       
                        <?php printf($this->__('Github Id #: %s', '<strong><a target="_blank" href='.$html_url.'>'.$githubId.'</a></strong>')) ?>
                    </p>
                    <?php endif; ?>
                    <?php if(!empty($github_username)): ?>
                    <p>
                        <?php printf($this->__('Username: %s', '<strong>'.$github_username.'</strong>')) ?>
                    </p>
                    <?php endif; ?>
                    <?php if(!empty($fullname)): ?>
                    <p>
                        <?php printf($this->__('Fullname: %s', '<strong>'.$fullname.'</strong>')) ?>
                    </p>
                    <?php endif; ?>
                    <?php if(!empty($company)): ?>
                    <p>
                        <?php printf($this->__('Company: %s', ($company) ? '<strong>'. $company .'</strong>' : '-')) ?>
                    </p>
                    <?php endif; ?>                
                </div>
                <div class="col-3" style="clear:both;">
                    <div class="clearer">&nbsp;</div>
                </div>
            </div>
        </div>
    </div>
    <?php else: ?>
    <div class="col2-set">
        <div class="box-content">
            <div class="col-1">
                <p>
                    <?php echo $this->__('You can connect store account with you Github account so you could login easier in the future.') ?>
                </p>
            </div>
           <div class="col-2">
                <div class="clearer">&nbsp;</div>
           </div>
        </div>
    </div>
    <?php endif; ?>    
</div>
<div class="buttons-set">
    <p class="back-link">
        <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>">
            <small>&laquo; </small>
            <?php echo $this->__('Back') ?>
        </a>
    </p>
</div>
